#memo
#NB: -port: host_port:container_port

secrets:
  jenkins_d2f_dockerhub_pwd:
    file: ./secrets/.d2f_dockerhub_pwd

volumes:
  jenkins_home:   

services:
  jenkins_controller:
    build: dockerfiles/.
    restart: on-failure
    privileged: true
    secrets:
      - jenkins_d2f_dockerhub_pwd
    user: root
    ports:
      - 8888:8080
      # - 50000:50000 (50000 is only useful for JNLP agent)
    container_name: jenkins_controller_container
    volumes:
      - jenkins_home:/var/jenkins_home
      #- /var/my-docker-volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      
  